project:
  type: default
  execute-dir: project # the working directory for computations
  output-dir: _outputs
  
author: 
  - name: Maël Delem
    orcid: 0009-0005-8518-1991
    email: mael.delem@univ-lyon2.fr
    corresponding: true
    url: https://emc.univ-lyon2.fr/equipes/memoire-emotion-et-attention-mea/delem-mael
    affiliations:
    - id: emc
      name: Study of Cognitive Mechanisms (EMC) Laboratory
      url: https://emc.univ-lyon2.fr
  - name: Rudy Purkart
    orcid: 0000-0002-5491-9958
    affiliations:
    - ref: emc
    - id: criugm
      name: Research Center of the Institut Universitaire de Gériatrie de Montréal (CRIUGM)
      url: https://www.criugm.qc.ca
  - name: Eddy Cavalli
    orcid: 0000-0003-3944-1973
    affiliations:
    - ref: emc
  - name: Virginie Ranson
    affiliations:
    - ref: emc
  - name: Charlotte Andrey
    affiliations:
    - ref: emc
  - name: Rémy Versace
    orcid: 0000-0002-4219-6617
    affiliations:
    - ref: emc
  - name: Gaën Plancher
    orcid: 0000-0002-0178-6207
    affiliations:
    - ref: emc
    - id: iuf
      name: Institut Universitaire de France (IUF)
      url: https://www.iufrance.fr

# --- Common options ---
# date: "08/06/2024"   # add the publication date if you want to
date-format: "DD/MM/YYYY"
date-modified: last-modified

bibliography:
  - "bibliography/references.bib" 
  - "bibliography/packages.bib"
csl: "bibliography/apa.csl"

execute:
  freeze: false
  warning: false
  error: false
  message: false

toc: true
number-sections: true

# --- Format-specific options ---
format:

  html:
    embed-resources: true  # self-contained HTML rendering
    format-links: false     # no links to other formats

    # styling
    theme: 
      dark: darkly
      light: flatly
    css: "utils/html/custom.css"
    # importing Montserrat font
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    mainfont: Montserrat
    fontsize: "medium"
    
    # interactive features
    lightbox: true          # clickable figures
    code-fold: true         # code folding for clarity
    code-annotations: hover # show code annotations on hover
    
    # HTML-specific TOC options
    toc-location: right
    toc-depth: 2
    toc-expand: 1
    number-depth: 2

  # Word
  docx: 
    reference-doc: "utils/docx/custom-reference-doc.docx"
    toc: false
    echo: false
    # extension to add a block with authors in .docx format
    filters:
      - authors-block

  # PDF - see https://github.com/quarto-journals/elsevier
  # elsevier-pdf:
  #   toc: false
  #   echo: false
  #   journal:
  #     cite-style: authoryear    
  #   # the option to include a new page after the abstract is commented out
  #   # the second one is to include a new page after the table of contents
  #   include-in-header:
  #     text: |
  #       % \newpageafter{abstract}
  #       \let\tableofcontentsORIG\tableofcontents
  #       \renewcommand\tableofcontents{\tableofcontentsORIG\clearpage}

# setting for proper numbering of sections
crossref: 
  chapters: true
  custom:
    - kind: float
      key: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
    - kind: float
      key: supptbl
      reference-prefix: Table S
      space-before-numbering: false

supptbl-cap-location: top
