---
title: Response to reviewers
author: "---"
format: docx
number-sections: false
---

Dear Dr. De Brigard,

 

We are pleased to submit a revised version of our manuscript entitled "*Are there unconscious visual images in aphantasia? Development of an implicit priming paradigm*" for consideration for publication in *Cognition*. We have addressed all the points raised by the reviewers and made the necessary changes to the manuscript. Below, we provide a point-by-point response to each of the reviewers' comments. We have mentioned the page and line number associated with each change based on the anonymised Word version of the manuscript.

We would like to thank the reviewers for their insightful comments and suggestions. We believe that their feedback has significantly improved the quality and clarity of our manuscript. We hope that the revised version of the manuscript meets the standards of *Cognition* and is suitable for publication.

 

Sincerely,

The Authors

{{< pagebreak >}}

# Reviewer 1

In this interesting and well written paper, the authors explore to what extent unconscious priming effects are preserved in individuals with aphantasia. Previous research has shown impaired effects of explicit imagination on perceptual readouts in individuals with aphantasia. I think the authors here rightfully argue that these effects might be tainted by demand characteristics, so the goal to test whether these effects might be preserved when imagination is induced automatically is a worthwhile endeavour. I have some suggestions and questions that I think will improve the paper if addressed.

First, I do not think that the present paper needs to rely on the concept of unconscious imagination. As the authors mention in the discussion as well, the extent to which the concept of unconscious imagination differentiates itself from mechanisms like working memory and prediction is somewhat controversial. The concept of unconscious imagination seems to have emerged from the aphantasia field by Nanay (2020), to describe cognitive processes that also involve top-down mechanisms in perception, but do not necessarily involve a subjective experience, and argue that these mechanisms might still be preserved in aphantasia, and thus unconscious imagination exists. I think the move to categorise these processes as unconscious imagination is only interesting to the extent to which this concept is coherent. In other words, it is only interesting to the extent we can make the claim that individuals with aphantasia are still "imagining" things, but they might just not be conscious of it. In contrast, if these mechanisms are not forms of imagination - and I think a strong case could be made that these aren't forms of imagination - finding preserved working memory and priming in aphantasia would be of much less significant empirical and theoretical value.

Please note that I do not think this would be hindrance to the present study. After all the present study finds that individuals with aphantasia are in fact impaired in an implicit priming task. I ask the authors to consider this as evidence that there might be a more broad deficit in the way the brain uses top-down information processing in perceptual inference, rather than a deficit that is specific to (unconscious) imagination. I realise that the authors mention the work on sensorimotor simulation as a possible overlapping mechanism. However, many have argued that the brains ability to form predictive signals on the basis of priors is a fundamental principle of cognitive function, and a deficit in such mechanisms have been theorised to underlie various sensory and cognitive aberrances, as seen in psychosis and autism. Since individuals with aphantasia seem to have a disturbance in these mechanisms thought to be fundamental to cognitive function, perhaps it would be useful if the authors connected to this line of work in their discussion a little bit more to discuss what the implications might be.

> We thank the reviewer for this comment. We agree on the idea that "unconscious imagination" or "unconscious mental imagery" might not be a relevant concept. Our results and their implications are in line with a recent discussion by @krempelAphantasiaInvoluntaryImagery2024 in favour of a true absence of visual imagery in aphantasia and against the elusive notion of an "unconscious" form of it. However, the hypothesis and concept of unconscious visual images in aphantasia is still prevalent in the literature [e.g., @liuProbingUnimaginableImpact2023, *inter alia*]and there is a need for empirical evidence to support the theoretical arguments against the very notion, especially considering that aphantasia is still largely identified using subjective reports. Consequently, we believe that maintaining the use of "unconscious mental imagery" is necessary, at least as an "anchor" concept that is being argued against.

> We thank the reviewer for the suggestion to discuss the hypothesis of perceptual inference and predictive signals deficits. However, we would argue that this hypothesis might be too strong: we think that showing that aphantasics do not process visual images for perceptual inference do not necessarily imply that they have a "*deficit in the way the brain uses* top-down information", but rather an *absence of the very information* to be processed, that is, visual images. Thus, they would not have a "general" deficit in the ability to form predictive signals, but an inability to form them from certain specific modalities. This would explain slower response times in certain very fast visual tasks similar to ours, but a typical functioning in more integrated tasks (working memory, etc.) by using other modalities to represent information. This point is discussed in Section 4.2, p.30.

As a minor comment, perhaps make it very clear that Jacobs 2018 is a N=1 study, and that these results (although widely cited), really requires further replication.

> We thank the reviewer for this suggestion. This precision was added on p.3, l.2-3: "Although on a N = 1 case study, this result may still suggest the existence of this unconscious form of imagery in aphantasia."

I was curious how strongly the effects in the implicit and explicit condition are correlated. It wouldn't undermine the findings in the present study, but it might be useful to know for the reader to what extent the implicit and explicit effects are separable.

> We thank the reviewer for this interesting interrogation. We computed a correlation between the two effects, and it is not significant ($\rho$ = 0.05, 95% CI \[-0.11, 0.21\], *p* = 0.57). Thus, the two effects indeed appear to be separable to some extent. We added this analysis in the Methods on p.18, l.1 and the Results on p.27, l.1.

Minor suggestions for the figures: Could the authors include some transitional probabilities in figure 2, so it is immediately clear which stimuli follow with which probabilities. The figure now seems to suggest that there is no preceding cue in the black gabor conditions, which I know is not the case from reading the methods.

Further, I think the data figures would be improved if they included individuals data points (violin or raincloud plots perhaps). Also, the plotted effect is a within subject effect, so within standard errors of the mean would be a more intuitive presentation of the results, rather than standard errors of the mean.

> We thank the reviewer for these suggestions. Figure 2 has been adjusted on p.10. For the response times Figures 5 and 6, the choice of representing the marginal means for the groups only was based on the important gap between individual mean response times (approximately ranging from 500 to 1000ms) and the effect size of interest (\~30ms). We added global figures with individual data points and "zoomed" versions to highlight the effect of interest for each task. This resulted in Figures 5 on p.20, 6 on p.22, 8 on p.24 and 9 on p.26.

When conducting Pearson correlations across groups, you need to control for group as in the presence of large mean differences in groups, a correlation can be driven by group differences, rather than a true linear relationship between the variables. In line with this, the claim about a continuum in the discussion should be softened.

> We thank the reviewer for spotting this oversight. We also later realised that the linearity assumption was not justified in our problem, especially considering the ordinal nature of the data and the underlying group structure mentioned. To relax this linearity assumption, we instead conducted Spearman correlations (i.e., on ranked data). Correlations with the OSIQ-O and SUIS remained significant, the correlation with the VVIQ became significant by a slight margin, but the conclusions were nuanced appropriately. Ranked correlations indeed allowed us to discuss the *monotonicity* (preservation of order) of the link, but not the linearity along a continuum, as has been pointed out here. The analytic process was corrected in the Methods on p.17, l.17-23, the Results have been modified on pp.26-27, and the discussion of these results has been adjusted on p.30, l.3-13.

Since a claim is being made about the existence of a null-effects in the aphantasia groups, it might be useful to report bayes factors in favour of the null-hypothesis.

> We thank the reviewer for suggesting Bayesian analyses. We fitted Bayesian models independently for aphantasic and control groups to assess the evidence in favour or against the existence of a congruence effect in these "sub-models". They confirmed strong evidence in favour of a null congruence effect in the aphantasia group in the implicit task ($BF_{01} = 14.12$) and explicit task ($BF_{01} = 12.09$), and extreme evidence in favour of a congruence effect in the control group in the implicit task ($BF_{01} < .001$) and explicit task ($BF_{01} < .001$). The description of the Bayesian modelling procedure can be found on p.16 l.16, and the results are mixed with the reports of model contrasts (and highlighted) throughout the Results.

Could the authors please discuss the limitations of their response mapping procedure. The responses aren't randomized (horizontal is always H and vice versa), which means participants could in theory learn the relationship between a cue and a button-press, rather than the effect of a cue on visual processing speed. How could this change the interpretation of the findings?

> Indeed, H was consistently Horizontal and V was Vertical. However, we would like to emphasize that there were as many congruent trials as incongruent ones, which, in our view, implies that participants could not reliably predict the correct response based on the cue alone. If they had responded solely based on the key they associated with the cue, only 50% of the responses would have been correct, which likely would have prevented the observation of a congruence effect. In light of this observation, we do not believe that learning the response key associated with the cue was a relevant or adopted strategy by the participants. Rather, we argue that the effect we measured was indeed related to the influence of a cue on visual processing speed, in line with our interpretation. We therefore suggest not adding this point to the discussion section to avoid overloading the manuscript.

Were there any differences in accuracy? Even if not, it might still be useful to report.

> We thank the reviewer for this suggestion. We initially removed errors as there were very few and they are usually not analysed in RT tasks, however we agree that this precision could be of interest for the reader to have a comprehensive picture of the results. Consequently, we analysed accuracy using logistic regression models to assess potential differences between the groups, before subsequently removing errors for RT analyses. Details of the analytic methods have been added on p.14, l.16-23 to describe the models, and results have been added on p.19, l.9-21. There were no accuracy differences between the groups.

{{< pagebreak >}}

# Reviewer 2

In this manuscript, the authors report on an experiment where they have developed a new implicit priming paradigm to test the hypothesis that aphantasics have unconscious mental imagery. Their results support that aphantasics do not have unconscious mental imagery, as they do not demonstrate a priming effect on the task. This is an interesting and well-designed paradigm which gets at a phenomenon which is not often tested in aphantasia research, and as such I think the manuscript would make an important contribution to the literature. However, I believe there are points which warrant substantial revisions in both the analysis conducted and the presentation of the work, and for this reason I would recommend acceptance following major revisions to the manuscript. Below I list points for the authors to address divided into major and minor issues, and I look forward to hearing the authors' responses to the concerns I raise.

"They found no differences in accuracy between the groups, but slower RTs and lower confidence in the aphantasics' answers and argued that this result was consistent with aphantasics having the visual images required to complete the task, albeit without conscious access to them." (p2) The authors here claim that visual images are required to complete the task, but it is not clear that this is in fact the case as alternative hypotheses aren't ruled out. It would be possible to encode information in a different format (e.g. linguistically) and still perform this task. Further, it is unclear why slower RT from aphantasic participants would imply that they still have visual images. Could the authors please clarify the connection between slower RT and lack of mental imagery.

> We thank the reviewer for this comment on the study of @liuProbingUnimaginableImpact2023. We acknowledge that any interpretation remains delicate and should be approached with caution when a task can be completed by encoding information in an alternative format (e.g., linguistically). It is particularly important to be mindful of this possibility in the tasks being proposed. In our own study, we made a concerted effort to account for this possibility by including a condition in which the Gabors had no color, thus preventing participants from employing the linguistic strategy of learning that all red Gabors had a specific orientation and responding solely based on their color. We believe that Liu and Bartolomeo also made their best effort to account for this possibility, although the extent of their success is likely debatable. As for the slower reaction times (RTs) observed in aphantasic individuals, this also remains difficult to interpret, and caution is warranted. Rather than attributing the slower RTs to the use of mental imagery, it is possible that alternative strategies, which take more time to implement, could explain the slower RTs. Liu and Bartolomeo themselves link slower RTs to lower confidence levels and suggest that this link reflects an inability to analyze their own mental processes, or in other words, to "know how they did it." However, we agree that this interpretation should be approached with caution.

> We reformulated to try and make this more explicit on p.2, l.17-20: "They found no differences in accuracy between the groups, but slower RTs and lower confidence in the aphantasics' answers, and argued that this result was consistent with aphantasics having the visual images required to succeed at the task , albeit without the knowledge of "how they did it"."

The authors use involuntary/unconscious somewhat interchangeably throughout the manuscript which makes it unclear what hypothesis they are actually intent on testing (p4). Note that involuntary and unconscious are not interchangeable as not all involuntary imagery is unconscious. For example, flashbacks (e.g., as in PTSD) and night-time dreams are cases of involuntary imagery, but these are still conscious. I urge the authors to not confuse involuntary for unconscious, and to be clearer about which cases they are interested in.

> We thank the reviewer for this key suggestion. Indeed, all unconscious imagery (if it exists) should be involuntary, but the reverse is not true. Our study focuses on providing evidence to test the idea of "unconscious mental images." We believe that showing no unconscious perceptual priming in aphantasia could help rule out the possibility of unconscious perceptual processing without the actual stimulus, which refers to "unconscious mental images" as described by @nanay_unconscious_2020. We replaced all imprecise wording throughout the manuscript.

"Consequently, the binocular rivalry paradigm developed by (Keogh & Pearson, 2018; like other objective measures based on explicit instructions to use mental imagery, e.g., Kay et al., 2022; Milton et al., 2021) cannot exclude the possible existence of involuntary and unconscious mental images in aphantasia. We aimed to fill this gap by designing an implicit priming task that would allow us to study unconscious mental images in aphantasia." (p4) This again seems to assume that involuntary and unconscious go hand in hand, but they actually dissociate (see the point just above). Are authors interested in testing 1) unconscious, or 2) involuntary, or 3) unconscious and involuntary imagery, in aphantasia? Please clarify throughout the manuscript.

> In line with the above comment, the correct concept at the heart of the hypotheses tested here is "unconscious". All imprecise wording has been replaced.

Figure 5 indicates that the response time for participants with aphantasia is consistently just below 680ms in the implicit task, but consistently around 800ms in the explicit task (p19). Is this a significant result? If so, why would it be the case that aphantasics are slower in the explicit task? If aphantasics have neither conscious nor unconscious imagery, should they not show more similar RTs on the implicit and explicit tasks?

> This result also puzzled us at first. It is important to first note that this slowing is observed in both populations, making it systematic rather than exclusive to individuals with aphantasia. Upon reflection, we thought that it might simply be a consequence of the experimental design. The implicit task is fast-paced, with a 500ms fixation, a 150ms cue and an immediate response. In contrast, the explicit task has a 500ms fixation, 1500ms letter cue, 3000ms imagery phase, another 500ms fixation followed finally by the response. That is, each answer was preceded by 5.5 seconds *and* participants were instructed to perform a conscious action (imagery), which might make it harder to find a "rhythm" and react quickly to the stimuli. This is one interpretation among many, but it could explain why the same effects appear at two different time scales (\~120ms later) *for both groups*: the same processes (i.e., hypothesised unconscious imagery for controls and absence thereof for aphantasics) are responsible for the priming effect, but its consequences are somehow slightly delayed by the events leading up to the response.

"Extremal VVIQ groups" should be "Extreme VVIQ groups" (p20). However, characterising the contrast as two extremes is misleading, as the control group consisted of participants who score was 42 or above on the VVIQ, which includes participants with a non-extreme score. An extreme (hyperphantasic) score is normally taken to be VVIQ $\geq$ 75 or VVIQ \$\geq\$80 (see e.g., Zeman (2024)). I would amend this here so that it does not imply that a score above 42 is extreme. I also recommend changing the introduction accordingly where the authors say they will discuss extreme scores, as they do in fact contrast aphantasics with average to extreme scores (and number of hyperphantasics are not reported). Also amend this in the caption of Figure 6, where 'groups at extreme ends of VVIQ' are mentioned. I would also suggest that the authors amend the discussion on p.6 in the Introduction, where they say that their results will shed light on a frequently asked questions in aphantasia research, namely whether there is a difference between aphantasics with VVIQ $\leq$ 16 (no imagery) and VVIQ between 17-32 (vague and dim). As far as I can see in the Results, the authors do not actually contrast these two groups. They seem to instead contrast the group VVIQ $\leq$ 16 with the group VVIQ between 42-80, but this does not get at the question which other authors have posed on p.6. as it only contrast VVIQ \$\leq\$16 with controls, but not VVIQ between 17-32 with controls. This point raises two major issues of revision. Firstly, as the authors are contrasting their aphantasia sample with controls from 42-80, this raises the possibility that their results could be skewed by hyperphantasics being included in the control group. I suggest the authors carry out analysis comparing aphantasics to the normal range of imagery (VVIQ between 55-60 is reported in Zeman et al (2020), McKelvie (1995), and Dance et al (2022)). Secondly, I suggest that the authors carry out analysis comparing total aphantasics (VVIQ $\leq$ 16) to moderate aphantasia (VVIQ between 17-32) in order to answer the question posed on p.6 and raised by many other researchers as noted.

> We thank the reviewer for this thorough recommendation and for spotting this oversight. The intuition here was correct: our sample comprises "total" aphantasics (VVIQ = 16, N = 50), "hypophantasics" [terminology of @reederNonvisualSpatialStrategies2024, VVIQ between 17 and 32, N = 39], and "controls" (VVIQ between 32 and 74) but only two hyperphantasics (VVIQ $\geq$ 75).

> Thus, we conducted a new analysis that could answer several questions raised here, by comparing these "finer-grained" groups of total aphantasics, hypophantasics, and controls, leaving out the two hyperphantasics. These analyses resulted in an interesting trend specific to the hypophantasic group, with a trend implicit effect but no explicit effect. We amended the introduction on p.6, l.12-23, the Methods on p.17, l.6-15, the Results on pp.22-25, and these new pattern are discussed on p.29, l.10-19. The conclusion on p.35 has also been modified accordingly.

"We argue that this novel paradigm provides a strong base to develop implicit objective behavioural assessments of visual imagery, thereby opening promising avenues for a better objective characterization of aphantasia." (p25) What do authors mean by "better" here? Do they mean that it's better than binocular rivalry, galvanic skin response, automatic pupil dilation? If so, why? Is it more reliable? Please elaborate on what makes it better, and what it makes it better relative to.

> Studies using binocular rivalry, galvanic skin response, and automatic pupil dilation have greatly inspired us and made valuable contributions to the objective characterization of aphantasia. With our study, we aimed to provide an additional and original contribution, which, alongside the work of other teams, would contribute toward a better objective characterization of aphantasia. However, we wish to highlight the strengths and unique features of our paradigm, namely that it relies on implicit rather than explicit mental imagery, is easy to implement (requiring no expensive or complex equipment, just a computer), and can be conducted online, allowing for the recruitment of a wider sample. In our view, these strengths make our paradigm a significant contribution.

> The sentence has been modified to better reflect our thought on p.29, l.19: "We propose that this novel online paradigm provides a foundation to develop implicit, objective behavioural assessments of visual imagery using a minimal setup, thereby opening new avenues for a large-scale, objective characterization of aphantasia."

It is not clear why including the non-coloured condition makes it unlikely that a propositional (rather than imagery based) strategy could have been used by participants with aphantasia (p28). Please clarify the reasoning here.

> Our phrasing likely led to the assumption that the non-colored condition made the use of a propositional strategy unlikely, and it requires clarification. Our point is rather that this strategy would only be advantageous in the colored condition: as soon as the color of the target appears, participants using this strategy respond with the key corresponding to the orientation associated with the color of the Gabor, an association they have memorized verbally (e.g., "red means horizontal"). However, when the non-colored target appears, participants can no longer rely on the color of the target to use the propositional strategy and are thus forced to process the orientation of the lines. Since the colored and non-colored trials were presented randomly, it remains difficult to determine whether participants initially attempted the propositional strategy, realized its limited effectiveness, and subsequently decided to abandon it.

"Curiously, the analysis of questionnaire data yielded a significant difference between aphantasics and controls in reported spatial imagery, assessed by the spatial scale of the OSIQ, contrasting with previous studies on aphantasia that used this questionnaire and found no between-group differences (Bainbridge et al., 2021; Dawes et al., 2020; Keogh & Pearson, 2018)." (p29) The authors should take into account alternative explanations. For example, it could be explained by the different uses of cut-off points in aphantasia. The differing results here could potentially be explained by differences in how aphantasia groups are demarcated in different articles. The authors used VVIQ $\leq$ 16 to denote aphantasia, whereas the other studies use other cut-off points (see Blomkvist and Marks, 2023 and Blomkvist 2022 for discussions).

> The issue of the diversity of cut-off points chosen to define aphantasia across the literature is indeed pervasive and should be examined with care for any effects reported. However, the results reported here were those of the standard group defined by VVIQ $\leq$ 32, so this group did not depart much from those defined by the various studies cited. Thus, the statistical result found in the present study remains singular and puzzling, leading us towards the exploratory hypothesis we formulate later in the paragraph.

"In stark contrast, it is often implied that the absence of fast automatic predictive processing and simulation of sensory representations in aphantasia could be a major functional disadvantage (Blomkvist & Marks, 2023; see for instance Monzel et al., 2022), therefore framing the condition as mostly characterized by deficits and drawbacks." (p29) It is not clear that the authors cited here should be read in this way as they both caution against interpreting aphantasia as having an overly negative impact on a person's life. Moreover, it is unclear how the results of the current study would speak to this point. Please clarify. In general, the discussion in this final section strikes me as unnuanced as it fails to capture the points that other authors make in a fair light. I would suggest rewriting this section to better reflect the points made by other author rather than setting it out in an antagonistic way.

"This could shed new light on this condition and help to define aphantasia as a balanced state rather than a disorder." (p29) This paints other authors in the light of trying to show that it is a disorder, but this is exactly what they are denying. This discussion does not correctly represent the views stated by authors in articles cited, and mischaracterises them in important ways which I believe is unfortunate for the field of aphantasia research as a whole as many authors are particularly calling for aphantasia not to be pathologised. As suggested above, I would rewrite this discussion with more sensitivity to the issue of whether aphantasia is a disorder, a condition, or an individual difference.

> We thank the reviewer for these comments. Indeed, we acknowledge that this part of the discussion was not nuanced enough and we understated the "antagonistic" tone of certain paragraphs, this was a mistake on our end. This is especially true given recent occurrences of expressions on the subject by the authors cited, such as the discussion of Monzel (2023) or Blomkvist (2023), which we do not ignore, and we realise that several sentences could appear as oversimplifying the views of some authors. Section 4.4 on p.34 has been rewritten in an attempt to be more true to the current views in the field of aphantasia research and remove superfluous antagonistic formulations. Our point originally came from the observation of very similar accuracy between groups and across the imagery spectrum on our task, which we felt echoed the debate about benefits and drawbacks of aphantasia.

"\[…\] received renewed attention only nine years ago, when Zeman et al. (2015), in a study that has since become very popular" (p1) Strange word choice of 'popular'. Maybe instead refer to the fact that it's often cited?

> The wording was indeed inaccurate and has been replaced by "a study that has since been highly cited, coining the term "*aphantasia*" to refer to "reduced or absent voluntary imagery" on p.1, l.11.

Zeman et al. (2015) suggest that "We propose the use of the term 'aphantasia' to refer to a condition of reduced or absent voluntary imagery." (p1) The authors only mention an inability to generate mental images when citing this. Please amend.

> The definition has been corrected on p.1, l.12, same quote as above.

The authors keep referring the aphantasia as a 'condition' whilst recognising the heterogeneity of it. I would recommend looking at Blomkvist and Mark's (2023) discussion of whether aphantasia should even be classified as a condition given what we currently know, and to incorporate this into the present article.

> We thank the reviewer for this comment. The characterisation of aphantasia as a disorder, a condition, or an individual difference is indeed of primary importance, and our choice of words needs to reflect our view and be consistent throughout the article. We added a discussion of Blomkvist and Marks (2023) in Section 4.4, p.34, and chose to harmonise the wording throughout the article by simply using the term "aphantasia" when referring to it.

The author discusses Nanay's hypothesis that some people with aphantasia could have intact unconscious imagery based on a study from Jacobs et al. (2018), but does not mention Blomkvist's (2022) argument against this interpretation of the data (p2). I would suggest that authors incorporate this into their discussion for a more nuanced discussion. I would also suggest that the authors actually define here what they mean by 'unconscious mental imagery' as this is not clear.

> We thank the reviewer for this suggestion. We added a mention of Blomkvist's (2022) views to this paragraph on p.3, l.11-14 "On the other hand, several studies that sought to develop objective measures assessing visual imagery found consistent behavioural and physiological differences between aphantasics and controls on imagery tasks, thus challenging Nanay's (2020) hypothesis of unconscious mental imagery in aphantasia (see also Blomkvist, 2022). Aphantasics have been shown to have a reduced skin conductance response \[...\]"

> As mentioned earlier, the terms used throughout the article will be harmonised and the unconscious mental imagery at stake here was better defined on p.2, l.10-13.

The author cites the Jacobs et al. (2018) study as potential evidence for unconscious imagery in aphantasia, but ignore the results from Keogh and Pearson (2019) which speak against this (p2). This is moreover both discussed in Nanay (2020) and Blomkvist (2023) and would be relevant to mention here.

> The results speaking against this interpretation of Jacobs' experiment and the idea of unconscious imagery (Keogh & Pearson, 2018, cited also by Blomkvist, 2022) are detailed in the subsequent paragraph. The structure we chose was to expose arguments brought forward by teams supporting the "unconscious imagery" hypothesis, then the opposite view. We apologize if this structure was unclear at the time of reading.

"This possibility, often raised in discussions about the condition, prevents from firmly concluding from these results that unconscious mental images exist in aphantasia." (p3) Citations missing for these discussions.

> Citations of Jacobs et al. (2018), Knight et al. (2022), Liu & Bartolomeo (2023) and Monzel et al. (2021) have been added on p.3, l.8-9.

"On the other hand, several studies that sought to develop objective measures assessing visual imagery found behavioural and physiological differences between aphantasics and controls, such as aphantasics having no skin conductance response to frightening scenarios (Wicken et al., 2021), no automatic pupil dilatation in reaction to imagined bright stimuli (Kay et al., 2022), or no priming by visual imagery (Keogh & Pearson, 2018), suggesting that aphantasics are truly unable to produce mental images." (p3) Results are reported in a misleading way here. Neither of these studies found no skin conductance response/pupil dilation/priming, but rather found that these effects were reduced. Please rewrite to clearly clarify the findings from the respective studies.

> We clarified this aspect on p.3, l.15 to 18, all mentions of "no effect" were replaced by "reduced effect".

Add recent study by Krempel and Monzel to discussion about involuntary imagery (p4). The study can be found here: https://pubmed.ncbi.nlm.nih.gov/38564857/

> This recent review by Krempel and Monzel is indeed very relevant for the subject of our study. We added their views on p.30, l.18-22.

The discussion of Muraki et al (2023) is confusing, as the authors talk about how self-diagnosed participants were asked to form voluntary images, and this could have skewed results as they were asked to do something they believe they couldn't (p4). However, Muraki et al. (2023) is not a study, it is a review article without any new empirical work. Which study are authors referring to here?

> This refers to the theoretical discussion of Muraki et al. (2023) of the concept of unconscious mental imagery, its implications, and the challenges it poses both to confirm or refute its existence. This mention in the introduction was superfluous and added nothing to the point, so it has been removed.

"If aphantasia relies only on a difficulty to access mental images, a priming effect should be observed for both groups in the implicit task, but not in the explicit one. If aphantasia relies on a genuine difficulty in creating mental images, no priming effect should be observed for the aphantasia group neither in the implicit nor in the explicit task, as opposed to the control group." (p6) This section talks about aphantasia as a problem of accessing mental images. However, the sections in the introduction focus on discussing involuntary imagery and unconscious imagery. It would be helpful for the reader if the hypotheses were put in that language here too, to make a clearer link between the cases. If I understand correctly, the authors are suggesting a contrast between a voluntary and an involuntary task, and hypothesising that if aphantasics retain unconscious imagery, then no priming effect should be observed for aphantasics in either the involuntary or voluntary task (whereas priming effect should be observed for controls).

> We adjusted the wording for consistency and clarity. The new sentence is: "If aphantasics have only difficulties with conscious mental imagery, a priming effect should be observed for both groups in the implicit task, but not in the explicit one. If aphantasics have difficulties with both conscious and unconscious mental imagery, no priming effect should be observed for the aphantasia group neither in the implicit nor in the explicit task, as opposed to the control group." (on p.6, l.7-11)

"("Perfectly clear and vivid as if it were a normal vision")." (p8) Typo, remove "a".

> The typo was corrected on p.8, l.10.

Final scoring is reported for the SUIS but not the VVIQ (p8). Amend for consistency.

> The VVIQ score range (16-80) was added on p.8, l.11.

"This result was also present when adopting a more conservative definition of aphantasia by analysing groups restricted to aphantasics scoring at floor VVIQ and controls with high VVIQ scores." (p24) It is misleading to say that a VVIQ of 42 is high. Most scores above 42 will be in the average range.

> This discussion was amended on p.29, l.10-20 to reflect the results of the new analyses mentioned earlier that replaced this.

"This result supports the hypothesis that aphantasia may be associated with a reduction or absence of mental image generation, even unconscious, as opposed to a lack of conscious access to mental images."(p24) "may be associated with" is too vague. Be clearer about the relationship.

> This sentence has been rephrased on p.28, l.11-14: "This result supports the hypothesis that aphantasics have difficulty generating both conscious and unconscious mental images, rather than only conscious ones. "

"The explicit task with instructions to produce mental imagery was inspired by the binocular rivalry paradigm developed by Keogh & Pearson (2018) and managed to replicate their pattern of results showing an absence of priming in aphantasia, thus validating the effectiveness of priming tasks to evidence conscious mental imagery differences." (p24) It would be relevant here to point out that the priming effect from Keogh and Pearson (2018) is not the same as the priming effect in the current study, as the current study was not in fact assessing binocular rivalry by presenting different stimuli to the two eyes at the same time.

> We thank the reviewer for spotting this oversight. This precision was added on p.29, l.1-3: "The explicit task with instructions to produce mental imagery was inspired by the binocular rivalry paradigm developed by Keogh (2018) and produced a similar pattern of results showing an absence of priming in aphantasia with a different task, thus validating the effectiveness of priming tasks to evidence conscious mental imagery differences."

"It is interesting to observe that our paradigm correlates with rather ecological forms of visual imagery." (p25) Do the authors mean to imply that the VVIQ items are not ecological? Most of them seem to be, comprising e.g., of imagining a person you know well or a shopfront. Please elaborate on this claim to clarify whether the VVIQ contains non-ecological items and why these should be taken to be non-ecological.

> Our wording was also inaccurate here. By "ecological", we meant to designate the broader scope of the SUIS and OSIQ, which also probe the use of different forms of imagery in daily life, whereas the VVIQ is focused on the immediate experience upon filling the questionnaire.

> However, based on a suggestion by another reviewer, we corrected our method for the correlational analyses and conducted Spearman (i.e., ranked) correlations instead of Pearson correlations to account for the ordinal nature of questionnaire responses and the inability to make the claim of a linear relationship between continuous questionnaires scores and congruence effects. The results of these new analyses showed that the correlations with the VVIQ were in the same range as those of the OSIQ and SUIS, but that they might be driven by group differences. The entire correlation results part has been corrected accordingly and this discussion paragraph changed entirely on p.30, l.3-13.

"However, this raises the question of whether our study assessed "mental imagery", as it is commonly defined as a conscious and voluntary experience." (p26) Please provide citations for this claim. In fact, many definitions do not have a take on whether this has to be voluntary and conscious and instead claim the opposite (see for example, Pearson (2019), Nanay (2020)).

> We thank the reviewer for this comment. The sentence here was indeed inaccurate, as the problem we eventually discuss is whether the concept of "unconscious imagery" is relevant. This introductory sentence was revised on p.30, l.16-19.

The authors start section 4.2 by discussing whether their study is really targeting unconscious mental imagery and then go on to discuss claims made by Muraki et al. regarding sensorimotor stimulation (pp26-27). I'm not sure this is the most relevant material to draw on. Nanay's conception of unconscious mental imagery seems more appropriate. The final sentence in this section is also somewhat difficult to parse, please consider rephrasing.

> We thank the reviewer for this suggestion. Indeed, Nanay's (2020) views were very important in the field of aphantasia to define the concept of unconscious mental imagery which is at the heart of the present study. We added a discussion of these views in the same paragraph on p.30, l.19-22.

"This type of strategy could even have been detrimental, which could explain slower response times in the uncoloured condition than in the coloured condition." (p28) What do authors mean by "detrimental" here, it seems like a strange choice of word? Consider rewording.

> The wording is indeed inaccurate here. We used the word in the meaning of "counter-productive", and replaced it accordingly on p.32, l.15.

"Large differences in spatial imagery ability also existed within the aphantasic group, hinting that this finding could be specifically tied to our sample and, more generally, that there could exist various sub-types in aphantasia characterized by their variable reliance on different forms of mental representations (e.g., spatial, verbal, kinaesthetic)." (p29) This seems like a rather odd suggestion. It is commonplace to suggest that there are different kinds of aphantasia based on different sensory modalities (auditory, visual, olfactory, gustatory, tactile), as well as other systems (affective, motor). But something like "verbal aphantasia" seems like a contradiction in terms as aphantasia explicitly has to do with mental imagery (a form of mental representation) and a verbal representations are per definition not imagistic.

> This sentence indeed needs to be rephrased to better serve its original purpose, which was primarily to suggest that various sub-types of aphantasia may exist, affecting different forms of mental representation (e.g., spatial), sensory modalities (e.g., auditory, visual, olfactory, gustatory, tactile), or systems (e.g., affective, motor).

"Furthermore, it has not yet been proven that aphantasia is a pathological disorder Blomkvist & Marks (2023)." (p29) This point could be put a bit more delicately, as it seems to imply that researchers are trying to prove this and that we should expect that it will be proven. It would also be relevant to cite Monzel et al. (2023) here as this is the study which investigates the question, which Blomkvist and Marks then discuss.

> As we acknowledged in response to a previous comment, our tone was too rough in some places and lacked nuance. This was adjusted throughout the discussion, and indeed here on p.34, l.6: " Furthermore, it has been shown that aphantasia does not meet the criteria of a pathological disorder (Monzel et al., 2023; Blomkvist & Marks, 2023)."

"In sum, our findings provided evidence suggesting that aphantasia does not only result from lacking metacognition but might reflect an actual alteration (whether a reduction or an absence) of both conscious and unconscious mental imagery." (p29) This conclusion is too broad as authors only tested VVIQ $\leq$ 16, and the parenthesis mention reduction in mental imagery (which I take to imply 17-32) but the authors only investigated a sample of participants with VVIQ $\leq$ 16.

> In line with previous comments, this final sentence on p.35, l.2-7 was adjusted to better reflect the results and nuance the findings: "In sum, our findings provide evidence suggesting that "total" aphantasia (defined by a VVIQ score of 16) may not solely result from impaired metacognition but could indicate an underlying reduction in both conscious and unconscious mental imagery. Additionally, a trend in the results indicated that hypophantasia (i.e., reduced imagery, VVIQ scores between 17 and 32) may involve the presence of unconscious imagery, albeit without the capacity for voluntary imagery generation."

{{< pagebreak >}}

# References {.unnumbered}

::: {#refs}
:::
